### PR TITLE
Properly support firework conversion and multiple effects.

### PR DESCRIPTION
**Pull request by jb-aero**

### CODE REVIEW

**Comment by PseudoKnight** [comment]
This still breaks backwards compatibility, when it's entirely avoidable.

**Comment by jb-aero** [comment]
If you got an email, that wasn't me pushing forward a fix, it just wouldn't let me switch branches without committing my local changes.

**Comment by PseudoKnight** [comment]
It's a step closer, but it still fails in certain cases. You're forgetting about launch_firework, for one. I still strongly support using the firework: array(strength: 1, effects(array(), array(), array())) format for optimal compatibility.

**Comment by jb-aero** [comment]
The way I've done it should accept that format, but it will tell them it is deprecated. Unless you mean writing to an array.

**Comment by LadyCailin** [comment]
Just to clarify, you have more things you want to do with this PR, correct?

**Comment by PseudoKnight** [comment]
It needs more things if he doesn't want to break scripts unnecessarily. And even if we were to ignore my disagreement with the array format (boo), he'd still need to support launch_firework since he wants to deprecate that format.

**Comment by jb-aero** [comment]
Just going to close this until it's done.

**Pull request closed without merging**
