### PR TITLE
Fixes CMDHELPER-3060

### PR DESCRIPTION
**Pull request by PseudoKnight**
Tested on 1.7.2 and 1.8.3 just to make sure it's all working this time.

### CODE REVIEW

**Comment by PseudoKnight** [comment]
Oh, I didn't use invokeMethod() here, but is that really needed? It seemed to test fine in 1.7.2.

**Comment by PseudoKnight** [comment]
It seems like it only ever could be an issue if they removed the deprecated methods. But they're only deprecated in Spigot right now.

**Comment by PhanaticD** [comment]
pls yes

**Comment by PseudoKnight** [comment]
Alternatively we could continue to build against Bukkit and I could use invokeMethod on the Spigot-only methods as well.

**Pull request merged**
